### ISSUE TITLE
Login example in admin page

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#13]
page: https://learn.gramener.com/guide/admin/

while `auth` is supported for accessing `admin`, it's stated as

`The ADMIN_AUTH section is the same as specifying the auth: authorization on all admin pages.` [ref](https://learn.gramener.com/guide/admin/#admin-page)

and is unclear on the specifics.

adding an example as below will help:

```yaml
import:
  admin:
    ...
    ADMIN_AUTH:
      login_url: /$YAMLURL/login_endpoint
    ...
```
